export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ALL_EDIT_EMPLOYEES = "GET_ALL_EDIT_EMPLOYEES";
export const UPDATE_NAV_TITLE = "UPDATE_NAV_TITLE";
export const GET_ONE_EMPLOYEE_DATA = "GET_ONE_EMPLOYEE_DATA";

export const CREATE_PROJECT_NAME = "CREATE_PROJECT_NAME";
export const GET_ALL_MEASURES = "GET_ALL_MEASURES";
export const GET_THIS_PROJECT_MEASURES = "GET_THIS_PROJECT_MEASURES";
export const GET_PROJECTS_FOR_MANAGER = "GET_PROJECTS_FOR_MANAGER";

export const GET_PROJECTS_FOR_EMPLOYEE = "GET_PROJECTS_FOR_EMPLOYEE";
export const GET_PEERS_FOR_PROJECT = "GET_PEERS_FOR_PROJECT";
export const GET_REMAINING_MEASURES = "GET_REMAINING_MEASURES";
export const GET_ONE_FEEDBACK = "GET_ONE_FEEDBACK";
export const GET_PROJECT_MEASURES = "GET_PROJECT_MEASURES";
